-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 19:55:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `imgURL` VARCHAR(512) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `ISO` VARCHAR(2) NOT NULL,
  `language` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ISO`));


-- -----------------------------------------------------
-- Table `mydb`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`version`));


-- -----------------------------------------------------
-- Table `mydb`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newsletter` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `newsletteremail` VARCHAR(255) NOT NULL,
  `subscribed_on` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `can_admin` SMALLINT NOT NULL DEFAULT 0,
  `can_manager` SMALLINT NOT NULL DEFAULT 0,
  `can_teacher` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`university` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `universityname` VARCHAR(255) NOT NULL,
  `universitycountry` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `universityname` (`universityname` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `status` SMALLINT NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `auth_key` VARCHAR(255) NULL DEFAULT NULL,
  `access_token` VARCHAR(255) NULL DEFAULT NULL,
  `logged_in_ip` VARCHAR(255) NULL DEFAULT NULL,
  `logged_in_at` TIMESTAMP NULL DEFAULT NULL,
  `created_ip` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `banned_at` TIMESTAMP NULL DEFAULT NULL,
  `banned_reason` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_email` (`email` ASC),
  UNIQUE INDEX `user_username` (`username` ASC),
  INDEX `user_role_id` (`role_id` ASC),
  CONSTRAINT `user_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `language` VARCHAR(2) NOT NULL,
  `courseName` VARCHAR(255) NOT NULL,
  `courseCategory` INT NOT NULL,
  `courseDescription` VARCHAR(2048) NOT NULL,
  `imageURL` VARCHAR(512) NOT NULL,
  `addDate` INT NOT NULL,
  `author` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx-course-author` (`author` ASC),
  INDEX `idx-course-courseCategory` (`courseCategory` ASC),
  INDEX `idx-course-language` (`language` ASC),
  INDEX `fk-course-author` (`author` ASC),
  INDEX `fk-course-courseCategory` (`courseCategory` ASC),
  INDEX `fk-course-language` (`language` ASC),
  CONSTRAINT `fk-course-author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE cascade,
  CONSTRAINT `fk-course-courseCategory`
    FOREIGN KEY (`courseCategory`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE cascade,
  CONSTRAINT `fk-course-language`
    FOREIGN KEY (`language`)
    REFERENCES `mydb`.`language` (`ISO`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `lessonTitle` VARCHAR(255) NOT NULL,
  `lessonDescription` VARCHAR(2048) NOT NULL,
  `courseID` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx-lesson-courseID` (`courseID` ASC),
  INDEX `fk-lesson-courseID` (`courseID` ASC),
  CONSTRAINT `fk-lesson-courseID`
    FOREIGN KEY (`courseID`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`note` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `notetext` VARCHAR(2048) NULL DEFAULT NULL,
  `FK_userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title` (`title` ASC),
  INDEX `idx-note-FK_userID` (`FK_userID` ASC),
  INDEX `fk-note-FK_userID` (`FK_userID` ASC),
  CONSTRAINT `fk-note-FK_userID`
    FOREIGN KEY (`FK_userID`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `timezone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profile_user_id` (`user_id` ASC),
  CONSTRAINT `profile_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `reviewtext` VARCHAR(1024) NOT NULL,
  `rating` INT NOT NULL,
  `FK_userID` INT NOT NULL,
  `FK_courseID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx-review-FK_courseID` (`FK_courseID` ASC),
  INDEX `idx-review-FK_userID` (`FK_userID` ASC),
  INDEX `fk-review-FK_courseID` (`FK_courseID` ASC),
  INDEX `fk-review-FK_userID` (`FK_userID` ASC),
  CONSTRAINT `fk-review-FK_courseID`
    FOREIGN KEY (`FK_courseID`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE cascade,
  CONSTRAINT `fk-review-FK_userID`
    FOREIGN KEY (`FK_userID`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unit` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `unitTitle` VARCHAR(250) NOT NULL,
  `unitText` TEXT NOT NULL,
  `imageURL` VARCHAR(512) NOT NULL,
  `lessonID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx-unit-lessonID` (`lessonID` ASC),
  INDEX `fk-unit-lessonID` (`lessonID` ASC),
  CONSTRAINT `fk-unit-lessonID`
    FOREIGN KEY (`lessonID`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`user_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_auth` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `provider` VARCHAR(255) NOT NULL,
  `provider_id` VARCHAR(255) NOT NULL,
  `provider_attributes` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_auth_provider_id` (`provider_id` ASC),
  INDEX `user_auth_user_id` (`user_id` ASC),
  CONSTRAINT `user_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`user_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_course` (
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `subscribed_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `course_id`),
  INDEX `idx-user_course-course_id` (`course_id` ASC),
  INDEX `idx-user_course-user_id` (`user_id` ASC),
  INDEX `fk-user_course-course_id` (`course_id` ASC),
  CONSTRAINT `fk-user_course-course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE cascade,
  CONSTRAINT `fk-user_course-user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE cascade);


-- -----------------------------------------------------
-- Table `mydb`.`user_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_token` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `type` SMALLINT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `data` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `expired_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_token_token` (`token` ASC),
  INDEX `user_token_user_id` (`user_id` ASC),
  CONSTRAINT `user_token_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `videoTitle` VARCHAR(45) NOT NULL,
  `videoDescription` VARCHAR(512) NOT NULL,
  `videoURL` VARCHAR(512) NOT NULL,
  `lessonID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx-video-lessonID` (`lessonID` ASC),
  INDEX `fk-video-lessonID` (`lessonID` ASC),
  CONSTRAINT `fk-video-lessonID`
    FOREIGN KEY (`lessonID`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE cascade);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
