<?php
/**
 * @var string $fname
 * @var string $lname
 */
?>

<p>

<tr>
    <td>
        <p>Hello <?= $fname ?> <?= $lname ?>,</p>
        <p> Thank you for contacting us. We'll try to get back to you as soon as possible.<br> <br>
            <b> This is an autogenerated response. Please do not reply to this email.</b>
            <br><br>Thank You,<br> </p>
           <br><br>
       <p style='color: #95999c;'> If this an error please kindly ignore this message. </p>
       <br><br>
    </td>
</tr>

</p>